export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_CHECKED = 'TOGGLE_CHECKED';
export const DELETE_TODO = 'DELETE_TODO';
export const SET_FILTER = 'SET_FILTER';
export const CLEAR_TODO = 'CLEAR_TODO';

export const VK_INIT = 'INIT';

export const SESSION_START = 'SESSION_START';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const PLAYLIST_USER_RECEIVED = 'PLAYLIST_USER_RECEIVED';
export const PLAYLIST_USER_PENDING = 'PLAYLIST_USER_PENDING';

export const ALBUMS_USER_RECEIVED = 'ALBUMS_USER_RECEIVED';
export const ALBUMS_USER_PENDING = 'ALBUMS_USER_PENDING';

export const PLAYER_PROGRESS = 'PLAYER_PROGRESS';
export const PLAYER_NEXT = 'PLAYER_NEXT';
export const PLAYER_PREV = 'PLAYER_PREV';
export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';
export const PLAYER_STOP = 'PLAYER_STOP';
export const PLAYER_LOAD = 'PLAYER_LOAD';
export const PLAYER_MUTE_TOGGLE = 'PLAYER_MUTE_TOGGLE';
export const PLAYER_END = 'PLAYER_END';
